trigger:
  branches:
    exclude:
      - master

stages:
  - stage: Build
    displayName: Docker build
    jobs:
      - job: buildudpserver
        displayName: build udp server
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          displayName: Build docker image
          inputs:
            command: build
            dockerfile: src/udp-server/Dockerfile
            tags: |
              $(Build.BuildId)
              latest
      - job: buildwebapp
        displayName: build web app
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          displayName: Build docker image
          inputs:
            command: build
            dockerfile: src/f1-telemetry-web/Dockerfile
            tags: |
              $(Build.BuildId)
              latest
      - job: buildmongobi
        displayName: build mongobi
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          displayName: Build docker image
          inputs:
            command: build
            dockerfile: src/mongobi/Dockerfile
            tags: |
              $(Build.BuildId)
              latest