version: "3.3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: f1-telemetry-mongo
    hostname: mongo
    volumes:
      - ${HOME}/f1-telemetry/mongo/data:/mongodata
    ports:
      - 27017:27017
    networks:
      - bridge
  mongo-express:
    image: mongo-express
    restart: always
    container_name: f1-telemetry-mongo-express
    ports:
      - 8081:8081
    networks:
      - bridge
    depends_on:
      - mongo
  # BI Connector
  mongobi:
    build: ./src/mongobi
    image: mongobi:latest
    restart: always
    volumes:
      - ${HOME}/f1-telemetry/mongobi/mongosqld.conf:/home/mongobi/mongosqld.conf
      - ${HOME}/f1-telemetry/mongobi/logs:/logs
    container_name: f1-telemetry-mongobi
    hostname: mongobi
    ports:
      - 3307:3307
    networks:
      - bridge
    depends_on:
      - mongo
  # UDP Server
  f1-telemetry-server:
    build: ./src/udp-server
    image: f1-telemetry-server:latest
    restart: always
    container_name: f1-telemetry-server
    environment: 
      - UDP_PORT=20777
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/f12020telemetry?retryWrites=true&w=majority
      - LOGS_PATH=/f1-telemetry/udp/logs
    volumes:
      - ${HOME}/f1-telemetry/udp/logs:/f1-telemetry/udp/logs
    ports:
      - 20777:20777
    networks:
      - bridge
    depends_on:
      - mongo
  # Web app
  f1-telemetry-web:
    build: ./src/f1-telemetry-web
    image: f1-telemetry-web:latest
    restart: always
    container_name: f1-telemetry-web
    ports:
      - 8080:80
    networks:
      - bridge
    depends_on:
      - mongobi

networks:
  bridge:
    driver: bridge