version: "3.3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/db:/mongodata
    ports:
      - 27017:27017
    networks:
      - bridge
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - bridge
    depends_on:
      - mongo
  # BI Connector
  mongobi:
    build: ./src/mongobi
    image: mongobi:latest # juky/mongobi
    restart: always
    volumes:
      - /home/rambo/mongobi/mongosqld.conf:/home/mongobi/mongosqld.conf
      - /home/rambo/mongobi/logs:/logs
    container_name: mongo-bi
    hostname: mongo-bi
    ports:
      - 3307:3307
    networks:
      - bridge
    depends_on:
      - mongo
  # UDP Server
  f1-telemetry-server:
    build: ./src/udp-server
    image: f1-telemetry-server:latest
    ports:
      - 20777:20777
    networks:
      - bridge
    depends_on:
      - mongo
  # Web app
  f1-telemetry-web:
    build: ./src/f1-telemetry-web
    image: f1-telemetry-web:latest
    ports:
      - 8080:80
    networks:
      - bridge
    depends_on:
      - mongobi

networks:
  bridge:
    driver: bridge